image: python:3.9-slim

stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip

cache:
  paths:
    - .cache/pip
    - .venv

before_script:
  - pip install poetry
  - poetry --version
  - poetry config virtualenvs.in-project true
  - poetry install -vv

check:
  stage: test
  only:
    - merge_requests
  script:
    - poetry run black .
    - poetry run isort .
    - poetry run mypy pydantic_bigquery tests
    - poetry run pylint pydantic_bigquery tests
    - export GOOGLE_APPLICATION_CREDENTIALS=$TEST_KEY_FILE
    - poetry run pytest

publish:
  stage: deploy
  only:
    - master
  variables:
    PYPI_UPLOAD_URL: "https://gitlab.com/api/v4/projects/21870843/packages/pypi"
  script:
    - poetry config repositories.timeisltd_upload ${PYPI_UPLOAD_URL}
    - poetry config http-basic.timeisltd_upload __token__ ${PYPI_UPLOAD_TOKEN}
    - poetry publish --build -r timeisltd_upload
